"""initial migration

Revision ID: bb44aaa63eb1
Revises:
Create Date: 2025-10-30 19:51:17.325660

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bb44aaa63eb1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "especialidad",
        sa.Column("id_especialidad", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nombre", sa.VARCHAR(length=80), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column("tarifa", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.PrimaryKeyConstraint("id_especialidad"),
        sa.UniqueConstraint("nombre"),
        schema="athome",
    )
    op.create_table(
        "estado_consulta",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("codigo", sa.String(), nullable=False),
        sa.Column("descripcion", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo", name="uq_estado_consulta_codigo"),
        schema="athome",
    )
    op.create_table(
        "provincia",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("nombre", sa.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre", name="uq_provincia_nombre"),
        schema="athome",
    )
    op.create_table(
        "relacion_solicitante",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre"),
        sa.UniqueConstraint("nombre", name="uq_rel_solicitante_nombre"),
        schema="athome",
    )
    op.create_table(
        "usuario",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("nombre", sa.VARCHAR(length=50), nullable=False),
        sa.Column("apellido", sa.VARCHAR(length=50), nullable=False),
        sa.Column("email", sa.VARCHAR(length=50), nullable=False),
        sa.Column("celular", sa.VARCHAR(length=50), nullable=True),
        sa.Column("es_solicitante", sa.Boolean(), nullable=False),
        sa.Column("es_profesional", sa.Boolean(), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("ultimo_login", sa.DateTime(), nullable=True),
        sa.Column("intentos_fallidos", sa.Integer(), nullable=False),
        sa.Column("bloqueado_hasta", sa.DateTime(), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("verificado", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "(es_profesional = TRUE) OR (es_solicitante = TRUE)",
            name="ck_usuario_al_menos_un_rol",
        ),
        sa.CheckConstraint(
            "NOT (es_profesional = TRUE AND es_solicitante = TRUE)",
            name="ck_usuario_roles_exclusivos",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_usuario_email"),
        schema="athome",
    )
    op.create_table(
        "departamento",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("provincia_id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.VARCHAR(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["provincia_id"], ["athome.provincia.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provincia_id", "nombre", name="uq_departamento_provincia_nombre"
        ),
        schema="athome",
    )
    op.create_index(
        "ix_departamento_provincia",
        "departamento",
        ["provincia_id"],
        unique=False,
        schema="athome",
    )
    op.create_table(
        "barrio",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("departamento_id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.VARCHAR(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["departamento_id"],
            ["athome.departamento.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "departamento_id", "nombre", name="uq_barrio_departamento_nombre"
        ),
        schema="athome",
    )
    op.create_index(
        "ix_barrio_departamento",
        "barrio",
        ["departamento_id"],
        unique=False,
        schema="athome",
    )
    op.create_table(
        "direccion",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("barrio_id", sa.UUID(), nullable=False),
        sa.Column("calle", sa.VARCHAR(length=100), nullable=False),
        sa.Column("numero", sa.Integer(), nullable=False),
        sa.Column("latitud", sa.Float(), nullable=True),
        sa.Column("longitud", sa.Float(), nullable=True),
        sa.CheckConstraint(
            "(latitud is null and longitud is null) or (latitud between -90 and 90 and longitud between -180 and 180)",
            name="ck_dir_latlon",
        ),
        sa.ForeignKeyConstraint(
            ["barrio_id"], ["athome.barrio.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="athome",
    )
    op.create_index(
        "ix_direccion_barrio",
        "direccion",
        ["barrio_id"],
        unique=False,
        schema="athome",
    )
    op.create_table(
        "profesional",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column("direccion_id", sa.UUID(), nullable=True),
        sa.Column(
            "activo",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "verificado",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("matricula", sa.VARCHAR(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["direccion_id"], ["athome.direccion.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"], ["athome.usuario.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("usuario_id", name="uq_profesional_usuario"),
        schema="athome",
    )
    op.create_table(
        "solicitante",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column("direccion_id", sa.UUID(), nullable=True),
        sa.Column(
            "activo",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["direccion_id"], ["athome.direccion.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"], ["athome.usuario.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("usuario_id", name="uq_solicitante_usuario"),
        schema="athome",
    )
    op.create_table(
        "disponibilidad",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("profesional_id", sa.UUID(), nullable=False),
        sa.Column("dias_semana", sa.Text(), nullable=False),
        sa.Column("hora_inicio", sa.Time(), nullable=False),
        sa.Column("hora_fin", sa.Time(), nullable=False),
        sa.CheckConstraint("hora_inicio < hora_fin", name="ck_disp_horas"),
        sa.ForeignKeyConstraint(
            ["profesional_id"], ["athome.profesional.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="athome",
    )
    op.create_index(
        "ix_disp_profesional",
        "disponibilidad",
        ["profesional_id"],
        unique=False,
        schema="athome",
    )
    op.create_table(
        "matricula",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("profesional_id", sa.UUID(), nullable=False),
        sa.Column("provincia_id", sa.UUID(), nullable=False),
        sa.Column("nro_matricula", sa.VARCHAR(length=50), nullable=False),
        sa.Column("vigente_desde", sa.Date(), nullable=False),
        sa.Column("vigente_hasta", sa.Date(), nullable=False),
        sa.CheckConstraint(
            "vigente_hasta >= vigente_desde", name="ck_matricula_fechas"
        ),
        sa.ForeignKeyConstraint(
            ["profesional_id"], ["athome.profesional.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["provincia_id"], ["athome.provincia.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "profesional_id",
            "provincia_id",
            "nro_matricula",
            name="uq_matricula_prof_prov_nro",
        ),
        schema="athome",
    )
    op.create_index(
        "ix_matricula_profesional",
        "matricula",
        ["profesional_id"],
        unique=False,
        schema="athome",
    )
    op.create_index(
        "ix_matricula_provincia",
        "matricula",
        ["provincia_id"],
        unique=False,
        schema="athome",
    )
    op.create_table(
        "paciente",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("nombre", sa.Text(), nullable=False),
        sa.Column("apellido", sa.Text(), nullable=False),
        sa.Column("fecha_nacimiento", sa.Date(), nullable=True),
        sa.Column("notas", sa.Text(), nullable=False),
        sa.Column("direccion_id", sa.UUID(), nullable=True),
        sa.Column("solicitante_id", sa.UUID(), nullable=False),
        sa.Column("relacion_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "fecha_nacimiento IS NULL OR fecha_nacimiento <= CURRENT_DATE",
            name="ck_paciente_fecha_nac_pasada",
        ),
        sa.ForeignKeyConstraint(
            ["direccion_id"], ["athome.direccion.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["relacion_id"],
            ["athome.relacion_solicitante.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["solicitante_id"], ["athome.solicitante.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("solicitante_id", name="uq_paciente_solicitante"),
        schema="athome",
    )
    op.create_table(
        "profesional_especialidad",
        sa.Column("profesional_id", sa.UUID(), nullable=False),
        sa.Column("especialidad_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["especialidad_id"],
            ["athome.especialidad.id_especialidad"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["profesional_id"], ["athome.profesional.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("profesional_id", "especialidad_id"),
        schema="athome",
    )
    op.create_index(
        "ix_prof_esp_especialidad",
        "profesional_especialidad",
        ["especialidad_id"],
        unique=False,
        schema="athome",
    )
    op.create_index(
        "ix_prof_esp_profesional",
        "profesional_especialidad",
        ["profesional_id"],
        unique=False,
        schema="athome",
    )
    op.create_table(
        "publicacion",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("profesional_id", sa.UUID(), nullable=False),
        sa.Column("especialidad_id", sa.Integer(), nullable=False),
        sa.Column("titulo", sa.Text(), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column("fecha_publicacion", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["especialidad_id"],
            ["athome.especialidad.id_especialidad"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["profesional_id"], ["athome.profesional.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="athome",
    )
    op.create_index(
        "ix_pub_especialidad",
        "publicacion",
        ["especialidad_id"],
        unique=False,
        schema="athome",
    )
    op.create_index(
        "ix_pub_profesional",
        "publicacion",
        ["profesional_id"],
        unique=False,
        schema="athome",
    )
    op.create_table(
        "consulta",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("paciente_id", sa.UUID(), nullable=False),
        sa.Column("profesional_id", sa.UUID(), nullable=False),
        sa.Column("direccion_servicio_id", sa.UUID(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("hora_inicio", sa.Time(), nullable=False),
        sa.Column("hora_fin", sa.Time(), nullable=False),
        sa.Column("estado_id", sa.Integer(), nullable=False),
        sa.Column("notas", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.CheckConstraint("hora_inicio < hora_fin", name="ck_consulta_horas"),
        sa.ForeignKeyConstraint(
            ["direccion_servicio_id"],
            ["athome.direccion.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["estado_id"], ["athome.estado_consulta.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["paciente_id"], ["athome.paciente.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["profesional_id"], ["athome.profesional.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="athome",
    )
    op.create_index(
        "ix_consulta_fecha",
        "consulta",
        ["fecha"],
        unique=False,
        schema="athome",
    )
    op.create_index(
        "ix_consulta_paciente",
        "consulta",
        ["paciente_id"],
        unique=False,
        schema="athome",
    )
    op.create_index(
        "ix_consulta_profesional",
        "consulta",
        ["profesional_id"],
        unique=False,
        schema="athome",
    )
    op.create_table(
        "valoracion",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("profesional_id", sa.UUID(), nullable=False),
        sa.Column("paciente_id", sa.UUID(), nullable=False),
        sa.Column("puntuacion", sa.Integer(), nullable=False),
        sa.Column("comentario", sa.Text(), nullable=True),
        sa.Column(
            "creado_en",
            sa.Date(),
            server_default=sa.text("CURRENT_DATE"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "puntuacion BETWEEN 1 AND 5", name="ck_valoracion_puntuacion_1_5"
        ),
        sa.ForeignKeyConstraint(
            ["paciente_id"], ["athome.paciente.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["profesional_id"], ["athome.profesional.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="athome",
    )
    op.create_index(
        "ix_valoracion_profesional_fecha",
        "valoracion",
        ["profesional_id", "creado_en"],
        unique=False,
        schema="athome",
    )
    op.create_table(
        "evento",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("consulta_id", sa.UUID(), nullable=False),
        sa.Column("tipo", sa.String(), nullable=False),
        sa.Column("datos", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["consulta_id"], ["athome.consulta.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="athome",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("evento", schema="athome")
    op.drop_index(
        "ix_valoracion_profesional_fecha",
        table_name="valoracion",
        schema="athome",
    )
    op.drop_table("valoracion", schema="athome")
    op.drop_index("ix_consulta_profesional", table_name="consulta", schema="athome")
    op.drop_index("ix_consulta_paciente", table_name="consulta", schema="athome")
    op.drop_index("ix_consulta_fecha", table_name="consulta", schema="athome")
    op.drop_table("consulta", schema="athome")
    op.drop_index("ix_pub_profesional", table_name="publicacion", schema="athome")
    op.drop_index("ix_pub_especialidad", table_name="publicacion", schema="athome")
    op.drop_table("publicacion", schema="athome")
    op.drop_index(
        "ix_prof_esp_profesional",
        table_name="profesional_especialidad",
        schema="athome",
    )
    op.drop_index(
        "ix_prof_esp_especialidad",
        table_name="profesional_especialidad",
        schema="athome",
    )
    op.drop_table("profesional_especialidad", schema="athome")
    op.drop_table("paciente", schema="athome")
    op.drop_index("ix_matricula_provincia", table_name="matricula", schema="athome")
    op.drop_index("ix_matricula_profesional", table_name="matricula", schema="athome")
    op.drop_table("matricula", schema="athome")
    op.drop_index("ix_disp_profesional", table_name="disponibilidad", schema="athome")
    op.drop_table("disponibilidad", schema="athome")
    op.drop_table("solicitante", schema="athome")
    op.drop_table("profesional", schema="athome")
    op.drop_index("ix_direccion_barrio", table_name="direccion", schema="athome")
    op.drop_table("direccion", schema="athome")
    op.drop_index("ix_barrio_departamento", table_name="barrio", schema="athome")
    op.drop_table("barrio", schema="athome")
    op.drop_index(
        "ix_departamento_provincia", table_name="departamento", schema="athome"
    )
    op.drop_table("departamento", schema="athome")
    # Drop refresh_tokens first (depends on usuario)
    op.drop_table("refresh_tokens", schema="athome")
    # Drop auditoria_login next
    op.drop_table("auditoria_login", schema="athome")
    # Now drop usuario
    op.drop_table("usuario", schema="athome")
    op.drop_table("relacion_solicitante", schema="athome")
    op.drop_table("provincia", schema="athome")
    op.drop_table("estado_consulta", schema="athome")
    op.drop_table("especialidad", schema="athome")
    # ### end Alembic commands ###
