"""add_auth_tables

Revision ID: 61513ea4632b
Revises: bb44aaa63eb1
Create Date: 2025-11-11 13:06:17.922803

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "61513ea4632b"
down_revision = "bb44aaa63eb1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auditoria_login",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("exitoso", sa.Boolean(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("motivo", sa.Text(), nullable=True),
        sa.Column(
            "fecha", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="athome",
    )
    op.create_index(
        op.f("ix_athome_auditoria_login_email"),
        "auditoria_login",
        ["email"],
        unique=False,
        schema="athome",
    )
    op.create_index(
        op.f("ix_athome_auditoria_login_fecha"),
        "auditoria_login",
        ["fecha"],
        unique=False,
        schema="athome",
    )
    op.create_index(
        op.f("ix_athome_auditoria_login_id"),
        "auditoria_login",
        ["id"],
        unique=False,
        schema="athome",
    )
    op.create_table(
        "refresh_tokens",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=500), nullable=False),
        sa.Column("expira_en", sa.DateTime(), nullable=False),
        sa.Column(
            "revocado", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column(
            "creado_en", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"], ["athome.usuario.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="athome",
    )
    op.create_index(
        op.f("ix_athome_refresh_tokens_id"),
        "refresh_tokens",
        ["id"],
        unique=False,
        schema="athome",
    )
    op.create_index(
        op.f("ix_athome_refresh_tokens_token"),
        "refresh_tokens",
        ["token"],
        unique=True,
        schema="athome",
    )
    op.create_index(
        op.f("ix_athome_refresh_tokens_usuario_id"),
        "refresh_tokens",
        ["usuario_id"],
        unique=False,
        schema="athome",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_athome_refresh_tokens_usuario_id"),
        table_name="refresh_tokens",
        schema="athome",
    )
    op.drop_index(
        op.f("ix_athome_refresh_tokens_token"),
        table_name="refresh_tokens",
        schema="athome",
    )
    op.drop_index(
        op.f("ix_athome_refresh_tokens_id"),
        table_name="refresh_tokens",
        schema="athome",
    )
    op.drop_table("refresh_tokens", schema="athome")
    op.drop_index(
        op.f("ix_athome_auditoria_login_id"),
        table_name="auditoria_login",
        schema="athome",
    )
    op.drop_index(
        op.f("ix_athome_auditoria_login_fecha"),
        table_name="auditoria_login",
        schema="athome",
    )
    op.drop_index(
        op.f("ix_athome_auditoria_login_email"),
        table_name="auditoria_login",
        schema="athome",
    )
    op.drop_table("auditoria_login", schema="athome")
    # ### end Alembic commands ###
